import type { NextPage } from "next";

const Page: NextPage = () => {
  return (
    <div>
      <h1 className="text-3xl">Delete this page?</h1>
      <ul>
        <li>Next.JS</li>
        <li>React</li>
        <li>Vercel</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
        <li>TypeScript</li>
      </ul>
    </div>
  );
};

export default Page;
